### ISSUE TITLE
terraform v0.11.2(vendoring)でCustomizeDiff利用時にSIGSEGV発生

### ISSUE THREAD

**Issue by yamamoto-febc** [sacloud/terraform-provider-sakuracloud#272]
以下のようなtfファイルの場合、`terraform apply`後の`terraform plan`などでSIGSEGVが発生する。

```hcl
resource "sakuracloud_server" "server01" {
  name = "server01"
  nic = "shared"
  ipaddress = ""
}
```

terraform v0.11.1だと発生しない。

<details>

```console
Error: Error running plan: 1 error(s) occurred:

* sakuracloud_server.server01: 1 error(s) occurred:

* sakuracloud_server.server01: unexpected EOF


panic: runtime error: invalid memory address or nil pointer dereference
2018-01-25T10:09:47.394+0900 [DEBUG] plugin.terraform-provider-sakuracloud_v1.0.5_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x184d5e7]
2018-01-25T10:09:47.394+0900 [DEBUG] plugin.terraform-provider-sakuracloud_v1.0.5_x4: 
2018-01-25T10:09:47.394+0900 [DEBUG] plugin.terraform-provider-sakuracloud_v1.0.5_x4: goroutine 70 [running]:
2018-01-25T10:09:47.394+0900 [DEBUG] plugin.terraform-provider-sakuracloud_v1.0.5_x4: github.com/sacloud/terraform-provider-sakuracloud/vendor/github.com/hashicorp/terraform/helper/schema.(*DiffFieldReader).readPrimitive(0xc4204e8ed0, 0xc420197340, 0x1, 0x1, 0xc4208fce10, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2018-01-25T10:09:47.394+0900 [DEBUG] plugin.terraform-provider-sakuracloud_v1.0.5_x4: 	/Development/workspace/go/src/github.com/sacloud/terraform-provider-sakuracloud/vendor/github.com/hashicorp/terraform/helper/schema/field_reader_diff.go:154 +0x207
2018-01-25T10:09:47.394+0900 [DEBUG] plugin.terraform-provider-sakuracloud_v1.0.5_x4: github.com/sacloud/terraform-provider-sakuracloud/vendor/github.com/hashicorp/terraform/helper/schema.(*DiffFieldReader).ReadField(0xc4204e8ed0, 0xc420197340, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2018-01-25T10:09:47.394+0900 [DEBUG] plugin.terraform-provider-sakuracloud_v1.0.5_x4: 	/Development/workspace/go/src/github.com/sacloud/terraform-provider-sakuracloud/vendor/github.com/hashicorp/terraform/helper/schema/field_reader_diff.go:67 +0x559
2018-01-25T10:09:47.394+0900 [DEBUG] plugin.terraform-provider-sakuracloud_v1.0.5_x4: github.com/sacloud/terraform-provider-sakuracloud/vendor/github.com/hashicorp/terraform/helper/schema.(*MultiLevelFieldReader).ReadFieldMerge(0xc42065e4c0, 0xc420197340, 0x1, 0x1, 0x1b7e70b, 0x7, 0x0, 0x0, 0x0, 0x0, ...)
2018-01-25T10:09:47.394+0900 [DEBUG] plugin.terraform-provider-sakuracloud_v1.0.5_x4: 	/Development/workspace/go/src/github.com/sacloud/terraform-provider-sakuracloud/vendor/github.com/hashicorp/terraform/helper/schema/field_reader_multi.go:45 +0x260
2018-01-25T10:09:47.394+0900 [DEBUG] plugin.terraform-provider-sakuracloud_v1.0.5_x4: github.com/sacloud/terraform-provider-sakuracloud/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceDiff).get(0xc4208f4380, 0xc420197340, 0x1, 0x1, 0x1b7e70b, 0x7, 0x0, 0x0, 0x0, 0x0, ...)
2018-01-25T10:09:47.394+0900 [DEBUG] plugin.terraform-provider-sakuracloud_v1.0.5_x4: 	/Development/workspace/go/src/github.com/sacloud/terraform-provider-sakuracloud/vendor/github.com/hashicorp/terraform/helper/schema/resource_diff.go:406 +0xe3
2018-01-25T10:09:47.394+0900 [DEBUG] plugin.terraform-provider-sakuracloud_v1.0.5_x4: github.com/sacloud/terraform-provider-sakuracloud/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceDiff).getChange(0xc4208f4380, 0x1b80487, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2018-01-25T10:09:47.394+0900 [DEBUG] plugin.terraform-provider-sakuracloud_v1.0.5_x4: 	/Development/workspace/go/src/github.com/sacloud/terraform-provider-sakuracloud/vendor/github.com/hashicorp/terraform/helper/schema/resource_diff.go:399 +0x340
2018-01-25T10:09:47.394+0900 [DEBUG] plugin.terraform-provider-sakuracloud_v1.0.5_x4: github.com/sacloud/terraform-provider-sakuracloud/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceDiff).GetChange(0xc4208f4380, 0x1b80487, 0x9, 0x19dc440, 0xc420196970, 0x0, 0xc4204e8f60)
2018-01-25T10:09:47.394+0900 [DEBUG] plugin.terraform-provider-sakuracloud_v1.0.5_x4: 	/Development/workspace/go/src/github.com/sacloud/terraform-provider-sakuracloud/vendor/github.com/hashicorp/terraform/helper/schema/resource_diff.go:330 +0x9e
2018-01-25T10:09:47.394+0900 [DEBUG] plugin.terraform-provider-sakuracloud_v1.0.5_x4: github.com/sacloud/terraform-provider-sakuracloud/sakuracloud.serverNetworkAttrsCustomizeDiff(0xc4208f4380, 0x1b601e0, 0xc4206830e0, 0xc42065e4a0, 0xc420171f40)
2018-01-25T10:09:47.394+0900 [DEBUG] plugin.terraform-provider-sakuracloud_v1.0.5_x4: 	/Development/workspace/go/src/github.com/sacloud/terraform-provider-sakuracloud/sakuracloud/resource_sakuracloud_server.go:852 +0x154
2018-01-25T10:09:47.394+0900 [DEBUG] plugin.terraform-provider-sakuracloud_v1.0.5_x4: github.com/sacloud/terraform-provider-sakuracloud/sakuracloud.composeCustomizeDiff.func1(0xc4208f4380, 0x1b601e0, 0xc4206830e0, 0xc420683620, 0xc4208f4380)
2018-01-25T10:09:47.394+0900 [DEBUG] plugin.terraform-provider-sakuracloud_v1.0.5_x4: 	/Development/workspace/go/src/github.com/sacloud/terraform-provider-sakuracloud/sakuracloud/customize_diff_func.go:13 +0x7d
2018-01-25T10:09:47.395+0900 [DEBUG] plugin.terraform-provider-sakuracloud_v1.0.5_x4: github.com/sacloud/terraform-provider-sakuracloud/vendor/github.com/hashicorp/terraform/helper/schema.schemaMap.Diff(0xc4204dea50, 0xc420085e50, 0xc4204e84e0, 0xc4206826a0, 0x1b601e0, 0xc4206830e0, 0xc42018c800, 0xc400000010, 0x1a25b80)
2018-01-25T10:09:47.395+0900 [DEBUG] plugin.terraform-provider-sakuracloud_v1.0.5_x4: 	/Development/workspace/go/src/github.com/sacloud/terraform-provider-sakuracloud/vendor/github.com/hashicorp/terraform/helper/schema/schema.go:435 +0xb62
2018-01-25T10:09:47.395+0900 [DEBUG] plugin.terraform-provider-sakuracloud_v1.0.5_x4: github.com/sacloud/terraform-provider-sakuracloud/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Diff(0xc4201f6690, 0xc420085e50, 0xc4204e84e0, 0x1b601e0, 0xc4206830e0, 0x1, 0xc4204e8570, 0xc4204e8570)
2018-01-25T10:09:47.395+0900 [DEBUG] plugin.terraform-provider-sakuracloud_v1.0.5_x4: 	/Development/workspace/go/src/github.com/sacloud/terraform-provider-sakuracloud/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:252 +0x187
2018-01-25T10:09:47.395+0900 [DEBUG] plugin.terraform-provider-sakuracloud_v1.0.5_x4: github.com/sacloud/terraform-provider-sakuracloud/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Diff(0xc4201f7030, 0xc420085e00, 0xc420085e50, 0xc4204e84e0, 0x257d458, 0x0, 0x18)
2018-01-25T10:09:47.395+0900 [DEBUG] plugin.terraform-provider-sakuracloud_v1.0.5_x4: 	/Development/workspace/go/src/github.com/sacloud/terraform-provider-sakuracloud/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:296 +0xa4
2018-01-25T10:09:47.395+0900 [DEBUG] plugin.terraform-provider-sakuracloud_v1.0.5_x4: github.com/sacloud/terraform-provider-sakuracloud/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Diff(0xc420682a20, 0xc420683160, 0xc42066fb10, 0x0, 0x0)
2018-01-25T10:09:47.395+0900 [DEBUG] plugin.terraform-provider-sakuracloud_v1.0.5_x4: 	/Development/workspace/go/src/github.com/sacloud/terraform-provider-sakuracloud/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:538 +0x57
2018/01/25 10:09:47 [ERROR] root: eval: *terraform.EvalDiff, err: unexpected EOF
2018/01/25 10:09:47 [ERROR] root: eval: *terraform.EvalSequence, err: unexpected EOF
2018/01/25 10:09:47 [TRACE] [walkPlan] Exiting eval tree: sakuracloud_server.server01
2018/01/25 10:09:47 [TRACE] dag/walk: upstream errored, not walking "provider.sakuracloud (close)"
2018/01/25 10:09:47 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2018/01/25 10:09:47 [TRACE] dag/walk: upstream errored, not walking "root"
2018-01-25T10:09:47.397+0900 [DEBUG] plugin: plugin process exited: path=/Users/kaz/bin/terraform-provider-sakuracloud_v1.0.5_x4
2018/01/25 10:09:47 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-01-25T10:09:47.398+0900 [WARN ] plugin: error closing client during Kill: err="connection is shut down"
```

</details>

**Comment by yamamoto-febc** [comment]
#274 によりvendoringしているTerraformのバージョンが v0.11.5になったことで解消。
