### ISSUE TITLE
作成中リソースを参照するとクラッシュする

### ISSUE THREAD

**Issue by yamamoto-febc** [sacloud/terraform-provider-sakuracloud#710]
スタックトレース

```
panic: runtime error: index out of range [0] with length 0

 goroutine 25 [running]:
 github.com/sacloud/terraform-provider-sakuracloud/sakuracloud.flattenVPCRouterGlobalNetworkMaskLen(...)
 	/Users/kaz/go/src/github.com/sacloud/terraform-provider-sakuracloud/sakuracloud/structure_vpc_router.go:177
 github.com/sacloud/terraform-provider-sakuracloud/sakuracloud.setVPCRouterResourceData(0x2260040, 0xc000278180, 0xc00069c070, 0xc00007dcc0, 0xc000283d40, 0xc00063f630, 0xc)
 	/Users/kaz/go/src/github.com/sacloud/terraform-provider-sakuracloud/sakuracloud/resource_sakuracloud_vpc_router.go:613 +0x1156
 github.com/sacloud/terraform-provider-sakuracloud/sakuracloud.dataSourceSakuraCloudVPCRouterRead(0xc00069c070, 0x1dad580, 0xc00007dcc0, 0x0, 0x0)
 	/Users/kaz/go/src/github.com/sacloud/terraform-provider-sakuracloud/sakuracloud/data_source_sakuracloud_vpc_router.go:439 +0x362
 github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).ReadDataApply(0xc000215800, 0xc0006a3ec0, 0x1dad580, 0xc00007dcc0, 0xc00040d928, 0x1, 0x0)
 	/Users/kaz/go/src/github.com/sacloud/terraform-provider-sakuracloud/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:398 +0x88
 github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).ReadDataApply(0xc00024e900, 0xc0001b99a0, 0xc0006a3ec0, 0xc0006a3ec0, 0x0, 0x0)
 	/Users/kaz/go/src/github.com/sacloud/terraform-provider-sakuracloud/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider.go:451 +0x8f
 github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadDataSource(0xc000188248, 0x2260080, 0xc00038e1b0, 0xc0007d0140, 0xc000188248, 0xc00038e1b0, 0xc000498a48)
 	/Users/kaz/go/src/github.com/sacloud/terraform-provider-sakuracloud/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:1036 +0x45d
 github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadDataSource_Handler(0x1f4c3c0, 0xc000188248, 0x2260080, 0xc00038e1b0, 0xc000278060, 0x0, 0x2260080, 0xc00038e1b0, 0xc00027c180, 0x16a)
 	/Users/kaz/go/src/github.com/sacloud/terraform-provider-sakuracloud/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3225 +0x217
 google.golang.org/grpc.(*Server).processUnaryRPC(0xc00045c580, 0x226b5e0, 0xc000702f00, 0xc000136100, 0xc000532ff0, 0x2b7e970, 0x0, 0x0, 0x0)
 	/Users/kaz/go/src/github.com/sacloud/terraform-provider-sakuracloud/vendor/google.golang.org/grpc/server.go:995 +0x460
 google.golang.org/grpc.(*Server).handleStream(0xc00045c580, 0x226b5e0, 0xc000702f00, 0xc000136100, 0x0)
 	/Users/kaz/go/src/github.com/sacloud/terraform-provider-sakuracloud/vendor/google.golang.org/grpc/server.go:1275 +0xd3d
 google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0005568f0, 0xc00045c580, 0x226b5e0, 0xc000702f00, 0xc000136100)
 	/Users/kaz/go/src/github.com/sacloud/terraform-provider-sakuracloud/vendor/google.golang.org/grpc/server.go:710 +0xa1
 created by google.golang.org/grpc.(*Server).serveStreams.func1
 	/Users/kaz/go/src/github.com/sacloud/terraform-provider-sakuracloud/vendor/google.golang.org/grpc/server.go:708 +0xa1

```

**Comment by yamamoto-febc** [comment]
再現率が低く実運用ではほぼ問題にならないと思われるため対応せずクローズとする。
問題が出てきたら再オープンする。
